### PR TITLE
adding microbenchmarks

### PR DESCRIPTION
**Pull request by HDCharles**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #24
* #22

Summary: added code to benchmark the primitives. Found that using
integer math for matmul primtive is faster with accuracy degredation so
update that primitive. quantize primitives are also faster with 32 bit
scale/zero_point/sums but results in accuracy degredation, need more robust
test to decide which to use.

results

benchmark_safe_int_mm.py https://gist.github.com/HDCharles/c7d2b88475a2695a12d4eedf3c7f0ce3
benchmark_q_dq.py https://gist.github.com/HDCharles/5b480764f5c1e50cf5bb20f9c401e2dc
benchmark_linear.py
 with no changes: https://gist.github.com/HDCharles/952458c2012554244ae30c0a7b94dcb5
 with int math and 32 bit scale/zp https://gist.github.com/HDCharles/ad3fc0be203a52cd440ec70ae5e4925a

Test Plan: python test/test_quant_primitives.py

Reviewers:

Subscribers:

Tasks:

Tags:

Differential Revision: [D45793204](https://our.internmc.facebook.com/intern/diff/D45793204)

### CODE REVIEW

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45793204).

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45793204).

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45793204).

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45793204).

**Comment by vkuzo** [comment]
let's move to ao_benchmarks?

I'd also recommend splitting adding new benchmarks versus improving things and capturing improvements in benchmarks into separate PRs.

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45793204).

**Comment by HDCharles** [comment]
@HDCharles has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45793204).

**Pull request closed without merging**
